name: Pipeline Java Teste Tecnico

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          architecture: x64
          check-latest: false
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install

      - name: Run Application Tests
        run: mvn test